[package]
name = "wifimic_server"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
flate2 = "1"
env_logger = "0.11"
sha2 = "0.10"
tar = "0.4"
thiserror = "2"
wifimic_diagnostics = { path = "../../crates/wifimic_diagnostics" }
wifimic_protocol = { path = "../../crates/wifimic_protocol" }
wifimic_update = { path = "../../crates/wifimic_update" }

[lints]
workspace = true
